# fly.toml app configuration file generated for notes973 on 2023-06-19T16:50:30+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "notes973"
primary_region = "cdg"

[env]
  PORT = "8080" # add this

[experimental]
auto_rollback = true

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
